---
title: "Publishing Shiny Apps on NCI's POSIT Connect Servers"
format: html
editor: visual
---

### Summary 

R Shiny apps can be deployed on NCI's POSIT connect server to enable sharing with NCI collaborators or external users. The process publishing shiny apps are described by CBIIT in [this article](https://service.cancer.gov/ncisp?id=nci_kb_article&sysparm_article=NCI-KB0015444).

From the CBIIT article: \
\
"R Shiny apps are interactive web applications built using the Shiny framework in R. They allow users to create graphical user interfaces (GUIs) for their R code, enabling others to interact with data and analyses without needing to install R or write code themselves.

R Shiny web apps can be made available for internal use on NCI's on premises Posit Connect server (positconnect.cancer.gov) or made available for external users on NCI's externally-facing Posit Connect server (appshare.cancer.gov), located in NCI's Cloud One. (Reference 1)"

This documentation will add further details and tips for CCBR members to develop and deploy shiny apps on the NCI POSIT connect server. \

### Developing Shiny Apps

CCBR's [Shiny Example](https://github.com/CCBR/shiny-example) repo can be used to explore how shiny apps are constructed and some basic features for shiny apps.

See the Deployment documentation page for further details.

### Deploying Shiny Apps

Shiny apps developed for NCI's POSIT Connect servers are typically deployed first on the internal development server: [appshare-dev.cancer.gov](appshare-dev.cancer.gov)

See the Deployment documentation page for further details on deploying a shiny apps to the internal development server.

### Final Publishing of Shiny Apps

After the shiny app has been tested and approved for publishing, it can then be published as an internal NCI facing app on the internal production server: [posit-connect-prod.cancer.gov](posit-connect-prod.cancer.gov)

Or the app can be published on the externally facing production server: [appshare.cancer.gov](appshare.cancer.gov)

See the Publishing documentation page for further details on publishing to either the internal or external servers.
