name: Feature request
description: Suggest an idea for the pipeline
labels: enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description of feature
      description: Please describe your suggestion for a new feature. It might help to describe a problem or use case, plus any alternatives that you have considered. Before submitting, please check if there is already an open issue for the same feature.
    validations:
      required: true
